# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: alg 1.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'alg 1.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0b\x61lg 1.proto\"\x1a\n\tHeartRate\x12\r\n\x05value\x18\x01 \x01(\r\"!\n\x10OxigenSaturation\x12\r\n\x05value\x18\x01 \x01(\r\"<\n\x15\x41rterialBloodPressure\x12\x10\n\x08systolic\x18\x01 \x01(\r\x12\x11\n\tdiastolic\x18\x02 \x01(\r\" \n\x0fSkinTemperature\x12\r\n\x05value\x18\x01 \x01(\x02\"\x1d\n\x0c\x42\x61tteryLevel\x12\r\n\x05value\x18\x01 \x01(\r\"0\n\x0cStepsCounter\x12\x11\n\tepochInit\x18\x01 \x01(\r\x12\r\n\x05steps\x18\x02 \x01(\rb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'alg 1_pb', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_HEARTRATE']._serialized_start=15
  _globals['_HEARTRATE']._serialized_end=41
  _globals['_OXIGENSATURATION']._serialized_start=43
  _globals['_OXIGENSATURATION']._serialized_end=76
  _globals['_ARTERIALBLOODPRESSURE']._serialized_start=78
  _globals['_ARTERIALBLOODPRESSURE']._serialized_end=138
  _globals['_SKINTEMPERATURE']._serialized_start=140
  _globals['_SKINTEMPERATURE']._serialized_end=172
  _globals['_BATTERYLEVEL']._serialized_start=174
  _globals['_BATTERYLEVEL']._serialized_end=203
  _globals['_STEPSCOUNTER']._serialized_start=205
  _globals['_STEPSCOUNTER']._serialized_end=253
# @@protoc_insertion_point(module_scope)
