# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: raw_data.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'raw_data.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0eraw_data.proto\"\xed\x01\n\x08Waveform\x12\r\n\x05\x65poch\x18\x01 \x01(\x04\x12\x11\n\x03ppg\x18\x02 \x01(\x0b\x32\x04.Ppg\x12\x11\n\x03imu\x18\x03 \x01(\x0b\x32\x04.Imu\x12\x1d\n\theartRate\x18\x04 \x01(\x0b\x32\n.HeartRate\x12+\n\x10oxigenSaturation\x18\x05 \x01(\x0b\x32\x11.OxigenSaturation\x12\x35\n\x15\x61rterialBloodPressure\x18\x06 \x01(\x0b\x32\x16.ArterialBloodPressure\x12)\n\x0fskinTemperature\x18\x07 \x01(\x0b\x32\x10.SkinTemperature\"{\n\x03Ppg\x12\x14\n\x0csamplingRate\x18\x01 \x01(\r\x12&\n\x0bppg_samples\x18\x02 \x03(\x0b\x32\x11.Ppg.Ppg_channels\x1a\x36\n\x0cPpg_channels\x12\x0b\n\x03red\x18\x01 \x01(\r\x12\n\n\x02ir\x18\x02 \x01(\r\x12\r\n\x05green\x18\x03 \x01(\r\"Y\n\x03Imu\x12\x14\n\x0csamplingRate\x18\x01 \x01(\r\x12\x1e\n\x03\x61\x63\x63\x18\x02 \x03(\x0b\x32\x11.Imu.Acceleration\x1a\x1c\n\x0c\x41\x63\x63\x65leration\x12\x0c\n\x04norm\x18\x01 \x01(\x02\"\x1a\n\tHeartRate\x12\r\n\x05value\x18\x01 \x01(\r\"!\n\x10OxigenSaturation\x12\r\n\x05value\x18\x01 \x01(\r\"<\n\x15\x41rterialBloodPressure\x12\x10\n\x08systolic\x18\x01 \x01(\r\x12\x11\n\tdiastolic\x18\x02 \x01(\r\" \n\x0fSkinTemperature\x12\r\n\x05value\x18\x01 \x01(\x02\"\x1d\n\x0c\x42\x61tteryLevel\x12\r\n\x05value\x18\x01 \x01(\r\"0\n\x0cStepsCounter\x12\x11\n\tepochInit\x18\x01 \x01(\r\x12\r\n\x05steps\x18\x02 \x01(\rb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'raw_data_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_WAVEFORM']._serialized_start=19
  _globals['_WAVEFORM']._serialized_end=256
  _globals['_PPG']._serialized_start=258
  _globals['_PPG']._serialized_end=381
  _globals['_PPG_PPG_CHANNELS']._serialized_start=327
  _globals['_PPG_PPG_CHANNELS']._serialized_end=381
  _globals['_IMU']._serialized_start=383
  _globals['_IMU']._serialized_end=472
  _globals['_IMU_ACCELERATION']._serialized_start=444
  _globals['_IMU_ACCELERATION']._serialized_end=472
  _globals['_HEARTRATE']._serialized_start=474
  _globals['_HEARTRATE']._serialized_end=500
  _globals['_OXIGENSATURATION']._serialized_start=502
  _globals['_OXIGENSATURATION']._serialized_end=535
  _globals['_ARTERIALBLOODPRESSURE']._serialized_start=537
  _globals['_ARTERIALBLOODPRESSURE']._serialized_end=597
  _globals['_SKINTEMPERATURE']._serialized_start=599
  _globals['_SKINTEMPERATURE']._serialized_end=631
  _globals['_BATTERYLEVEL']._serialized_start=633
  _globals['_BATTERYLEVEL']._serialized_end=662
  _globals['_STEPSCOUNTER']._serialized_start=664
  _globals['_STEPSCOUNTER']._serialized_end=712
# @@protoc_insertion_point(module_scope)
